import { userRegisterStruct } from "../interface/Interface";

export const USERS: userRegisterStruct[] = [
    { 
        id: 1,
        email: "facundo_hernandez@mailtest.com",
        password: "facundo_hernandez",
        name: "Facundo", 
        lastname: "Hernandez",
        photo: "photo.jpg", 
    },
    { 
        id: 2,
        email: "camila_herrera@mailtest.com",
        password: "camila_herrera",
        name: "Camila", 
        lastname: "Herrara",
        photo: "photo2.jpg", 
    },
    { 
        id: 3,
        email: "test",
        password: "test",
        name: "Romina", 
        lastname: "Perez",
        photo: "photo3.jpg", 
    },
    { 
        id: 4,
        email: "carlos_montenegro@mailtest.com",
        password: "carlos_montenegro",
        name: "Carlos", 
        lastname: "Montenegro",
        photo: "photo4.jpg", 
    },
    { 
        id: 5,
        email: "marcos_ibaceta@mailtest.com",
        password: "marcos_ibaceta",
        name: "Marcos Ibaceta", 
        lastname: "Montenegro",
        photo: "photo5.jpg", 
    },
    { 
        id: 6,
        email: "oscar_roda@mailtest.com",
        password: "oscar_roda",
        name: "Oscar", 
        lastname: "Roda",
        photo: "photo6.jpg", 
    },
    { 
        id: 7,
        email: "milagros_reyes@mailtest.com",
        password: "milagros_reyes",
        name: "Milagros", 
        lastname: "Reyes",
        photo: "photo7.jpg", 
    },
    { 
        id: 8,
        email: "agustina_medina@mailtest.com",
        password: "agustina_medina",
        name: "Agustina", 
        lastname: "Medina",
        photo: "photo8.jpg", 
    },
    { 
        id: 9,
        email: "lorena_ruiz@mailtest.com",
        password: "lorena_ruiz",
        name: "Lorena", 
        lastname: "Ruiz",
        photo: "photo9.jpg", 
    },
    { 
        id: 10,
        email: "francisco_avila@mailtest.com",
        password: "francisco_avila",
        name: "Francisco", 
        lastname: "Ávila",
        photo: "photo10.jpg", 
    },
];